ci:
  autoupdate_schedule: monthly
  autofix_commit_msg: "style(pre-commit.ci): auto fixes [...]"
  autoupdate_commit_msg: "ci(pre-commit.ci): autoupdate"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-docstring-first
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.15
    hooks:
      - id: validate-pyproject
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.5.0
    hooks:
      - id: setup-cfg-fmt

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.7
    hooks:
      - id: ruff
        args: [--fix, --unsafe-fixes]

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.6.1
  #   hooks:
  #     - id: mypy
  #       files: "^src/"
  #       # # you have to add the things you want to type check against here
  #       # additional_dependencies:
  #       #   - numpy
