name: llsbuild
channels:
  - talley
  - conda-forge
  - defaults
dependencies:
  - python=3.5
  - pyinstaller
  - git
  - numpy
  - scipy
  - matplotlib
  - tifffile
  - numba
  - voluptuous
  - watchdog
  - pyqt
  - pyopencl
  - spimagine