# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\llspy\gui\img_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(907, 695)
        font = QtGui.QFont()
        font.setKerning(True)
        Dialog.setFont(font)
        Dialog.setAutoFillBackground(True)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.mainLayout = QtWidgets.QVBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.maxProjButton = QtWidgets.QPushButton(Dialog)
        self.maxProjButton.setMinimumSize(QtCore.QSize(0, 35))
        self.maxProjButton.setCheckable(True)
        self.maxProjButton.setAutoDefault(False)
        self.maxProjButton.setDefault(False)
        self.maxProjButton.setFlat(False)
        self.maxProjButton.setObjectName("maxProjButton")
        self.horizontalLayout.addWidget(self.maxProjButton)
        self.minProjButton = QtWidgets.QPushButton(Dialog)
        self.minProjButton.setEnabled(True)
        self.minProjButton.setMinimumSize(QtCore.QSize(0, 35))
        self.minProjButton.setCheckable(True)
        self.minProjButton.setAutoDefault(False)
        self.minProjButton.setDefault(False)
        self.minProjButton.setFlat(False)
        self.minProjButton.setObjectName("minProjButton")
        self.horizontalLayout.addWidget(self.minProjButton)
        self.meanProjButton = QtWidgets.QPushButton(Dialog)
        self.meanProjButton.setEnabled(True)
        self.meanProjButton.setMinimumSize(QtCore.QSize(0, 35))
        self.meanProjButton.setCheckable(True)
        self.meanProjButton.setAutoDefault(False)
        self.meanProjButton.setDefault(False)
        self.meanProjButton.setFlat(False)
        self.meanProjButton.setObjectName("meanProjButton")
        self.horizontalLayout.addWidget(self.meanProjButton)
        self.stdProjButton = QtWidgets.QPushButton(Dialog)
        self.stdProjButton.setEnabled(True)
        self.stdProjButton.setMinimumSize(QtCore.QSize(0, 35))
        self.stdProjButton.setCheckable(True)
        self.stdProjButton.setAutoDefault(False)
        self.stdProjButton.setDefault(False)
        self.stdProjButton.setFlat(False)
        self.stdProjButton.setObjectName("stdProjButton")
        self.horizontalLayout.addWidget(self.stdProjButton)
        self.infoButton = QtWidgets.QPushButton(Dialog)
        self.infoButton.setMinimumSize(QtCore.QSize(0, 35))
        self.infoButton.setCheckable(True)
        self.infoButton.setAutoDefault(False)
        self.infoButton.setDefault(False)
        self.infoButton.setFlat(False)
        self.infoButton.setObjectName("infoButton")
        self.horizontalLayout.addWidget(self.infoButton)
        self.mainLayout.addLayout(self.horizontalLayout)
        self.imgLayout = QtWidgets.QHBoxLayout()
        self.imgLayout.setContentsMargins(-1, 0, 5, -1)
        self.imgLayout.setObjectName("imgLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(20, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.minSlider = QtWidgets.QSlider(Dialog)
        self.minSlider.setOrientation(QtCore.Qt.Vertical)
        self.minSlider.setObjectName("minSlider")
        self.verticalLayout.addWidget(self.minSlider)
        self.minLabelk = QtWidgets.QLabel(Dialog)
        self.minLabelk.setObjectName("minLabelk")
        self.verticalLayout.addWidget(self.minLabelk)
        self.imgLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.maxSlider = QtWidgets.QSlider(Dialog)
        self.maxSlider.setOrientation(QtCore.Qt.Vertical)
        self.maxSlider.setObjectName("maxSlider")
        self.verticalLayout_3.addWidget(self.maxSlider)
        self.maxLabel = QtWidgets.QLabel(Dialog)
        self.maxLabel.setObjectName("maxLabel")
        self.verticalLayout_3.addWidget(self.maxLabel)
        self.imgLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gamSlider = QtWidgets.QSlider(Dialog)
        self.gamSlider.setMinimum(50)
        self.gamSlider.setMaximum(150)
        self.gamSlider.setProperty("value", 100)
        self.gamSlider.setOrientation(QtCore.Qt.Vertical)
        self.gamSlider.setObjectName("gamSlider")
        self.verticalLayout_4.addWidget(self.gamSlider)
        self.gamLabel = QtWidgets.QLabel(Dialog)
        self.gamLabel.setObjectName("gamLabel")
        self.verticalLayout_4.addWidget(self.gamLabel)
        self.imgLayout.addLayout(self.verticalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.imgLayout.addItem(spacerItem)
        self.mainLayout.addLayout(self.imgLayout)
        self.SliderLayout = QtWidgets.QVBoxLayout()
        self.SliderLayout.setContentsMargins(20, 0, 20, 12)
        self.SliderLayout.setObjectName("SliderLayout")
        self.Zwidget = QtWidgets.QWidget(Dialog)
        self.Zwidget.setObjectName("Zwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Zwidget)
        self.horizontalLayout_5.setContentsMargins(0, 1, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Zlabel = QtWidgets.QLabel(self.Zwidget)
        self.Zlabel.setMinimumSize(QtCore.QSize(15, 0))
        self.Zlabel.setMaximumSize(QtCore.QSize(15, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Zlabel.setFont(font)
        self.Zlabel.setScaledContents(False)
        self.Zlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Zlabel.setObjectName("Zlabel")
        self.horizontalLayout_5.addWidget(self.Zlabel)
        self.Zslider = QtWidgets.QSlider(self.Zwidget)
        self.Zslider.setOrientation(QtCore.Qt.Horizontal)
        self.Zslider.setObjectName("Zslider")
        self.horizontalLayout_5.addWidget(self.Zslider)
        self.ZsliderInfo = QtWidgets.QLabel(self.Zwidget)
        self.ZsliderInfo.setMinimumSize(QtCore.QSize(30, 0))
        self.ZsliderInfo.setText("")
        self.ZsliderInfo.setObjectName("ZsliderInfo")
        self.horizontalLayout_5.addWidget(self.ZsliderInfo)
        self.SliderLayout.addWidget(self.Zwidget)
        self.Cwidget = QtWidgets.QWidget(Dialog)
        self.Cwidget.setObjectName("Cwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Cwidget)
        self.horizontalLayout_6.setContentsMargins(0, 1, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Clabel = QtWidgets.QLabel(self.Cwidget)
        self.Clabel.setMinimumSize(QtCore.QSize(15, 0))
        self.Clabel.setMaximumSize(QtCore.QSize(15, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Clabel.setFont(font)
        self.Clabel.setScaledContents(False)
        self.Clabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Clabel.setObjectName("Clabel")
        self.horizontalLayout_6.addWidget(self.Clabel)
        self.Cslider = QtWidgets.QSlider(self.Cwidget)
        self.Cslider.setOrientation(QtCore.Qt.Horizontal)
        self.Cslider.setObjectName("Cslider")
        self.horizontalLayout_6.addWidget(self.Cslider)
        self.CsliderInfo = QtWidgets.QLabel(self.Cwidget)
        self.CsliderInfo.setMinimumSize(QtCore.QSize(30, 0))
        self.CsliderInfo.setText("")
        self.CsliderInfo.setObjectName("CsliderInfo")
        self.horizontalLayout_6.addWidget(self.CsliderInfo)
        self.SliderLayout.addWidget(self.Cwidget)
        self.Twidget = QtWidgets.QWidget(Dialog)
        self.Twidget.setObjectName("Twidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.Twidget)
        self.horizontalLayout_7.setContentsMargins(0, 1, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.fpsLabel = QtWidgets.QLabel(self.Twidget)
        self.fpsLabel.setObjectName("fpsLabel")
        self.horizontalLayout_7.addWidget(self.fpsLabel)
        self.fpsSpin = QtWidgets.QSpinBox(self.Twidget)
        self.fpsSpin.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fpsSpin.setReadOnly(False)
        self.fpsSpin.setMinimum(1)
        self.fpsSpin.setMaximum(60)
        self.fpsSpin.setProperty("value", 10)
        self.fpsSpin.setObjectName("fpsSpin")
        self.horizontalLayout_7.addWidget(self.fpsSpin)
        self.playButton = QtWidgets.QPushButton(self.Twidget)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout_7.addWidget(self.playButton)
        self.Tlabel = QtWidgets.QLabel(self.Twidget)
        self.Tlabel.setMinimumSize(QtCore.QSize(15, 0))
        self.Tlabel.setMaximumSize(QtCore.QSize(15, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Tlabel.setFont(font)
        self.Tlabel.setScaledContents(False)
        self.Tlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Tlabel.setObjectName("Tlabel")
        self.horizontalLayout_7.addWidget(self.Tlabel)
        self.Tslider = QtWidgets.QSlider(self.Twidget)
        self.Tslider.setOrientation(QtCore.Qt.Horizontal)
        self.Tslider.setObjectName("Tslider")
        self.horizontalLayout_7.addWidget(self.Tslider)
        self.TsliderInfo = QtWidgets.QLabel(self.Twidget)
        self.TsliderInfo.setMinimumSize(QtCore.QSize(30, 0))
        self.TsliderInfo.setText("")
        self.TsliderInfo.setObjectName("TsliderInfo")
        self.horizontalLayout_7.addWidget(self.TsliderInfo)
        self.SliderLayout.addWidget(self.Twidget)
        self.mainLayout.addLayout(self.SliderLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.mainLayout.addLayout(self.gridLayout)
        self.infoText = QtWidgets.QTextEdit(Dialog)
        self.infoText.setMinimumSize(QtCore.QSize(0, 200))
        self.infoText.setMaximumSize(QtCore.QSize(16777215, 200))
        self.infoText.setFrameShadow(QtWidgets.QFrame.Plain)
        self.infoText.setLineWidth(8)
        self.infoText.setReadOnly(True)
        self.infoText.setObjectName("infoText")
        self.mainLayout.addWidget(self.infoText)
        self.verticalLayout_6.addLayout(self.mainLayout)
        self.actionmax_proj = QtWidgets.QAction(Dialog)
        self.actionmax_proj.setObjectName("actionmax_proj")
        self.Tlabel.raise_()
        self.Zlabel.raise_()
        self.Cslider.raise_()
        self.fpsSpin.raise_()
        self.Zslider.raise_()
        self.infoText.raise_()
        self.fpsLabel.raise_()
        self.Clabel.raise_()
        self.playButton.raise_()
        self.Tslider.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.maxProjButton.setText(_translate("Dialog", "Max Projection"))
        self.minProjButton.setText(_translate("Dialog", "Min Projection"))
        self.meanProjButton.setText(_translate("Dialog", "Mean Projection"))
        self.stdProjButton.setText(_translate("Dialog", "StdDev Projection"))
        self.infoButton.setText(_translate("Dialog", "Show Info"))
        self.minLabelk.setText(_translate("Dialog", "Min"))
        self.maxLabel.setText(_translate("Dialog", "Max"))
        self.gamLabel.setText(_translate("Dialog", "Gam"))
        self.Zlabel.setText(_translate("Dialog", "Z"))
        self.Clabel.setText(_translate("Dialog", "C"))
        self.fpsLabel.setText(_translate("Dialog", "fps"))
        self.playButton.setText(_translate("Dialog", "play"))
        self.Tlabel.setText(_translate("Dialog", "T"))
        self.actionmax_proj.setText(_translate("Dialog", "max proj"))
        self.actionmax_proj.setShortcut(_translate("Dialog", "M"))

