# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'llspy/gui/main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main_GUI(object):
    def setupUi(self, Main_GUI):
        Main_GUI.setObjectName("Main_GUI")
        Main_GUI.resize(617, 803)
        Main_GUI.setMinimumSize(QtCore.QSize(0, 803))
        Main_GUI.setFocusPolicy(QtCore.Qt.TabFocus)
        self.centralWidget = QtWidgets.QWidget(Main_GUI)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(593, 500))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_process = QtWidgets.QWidget()
        self.tab_process.setObjectName("tab_process")
        self.process_tab_layout = QtWidgets.QVBoxLayout(self.tab_process)
        self.process_tab_layout.setContentsMargins(11, 11, 11, 11)
        self.process_tab_layout.setSpacing(6)
        self.process_tab_layout.setObjectName("process_tab_layout")
        self.listbox = QtWidgets.QTableWidget(self.tab_process)
        self.listbox.setMinimumSize(QtCore.QSize(0, 200))
        self.listbox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listbox.setDragEnabled(True)
        self.listbox.setDragDropOverwriteMode(False)
        self.listbox.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.listbox.setAlternatingRowColors(True)
        self.listbox.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listbox.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listbox.setShowGrid(True)
        self.listbox.setGridStyle(QtCore.Qt.DashLine)
        self.listbox.setWordWrap(False)
        self.listbox.setCornerButtonEnabled(True)
        self.listbox.setColumnCount(7)
        self.listbox.setObjectName("listbox")
        self.listbox.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.listbox.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.listbox.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.listbox.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.listbox.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.listbox.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.listbox.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.listbox.setHorizontalHeaderItem(6, item)
        self.process_tab_layout.addWidget(self.listbox)
        self.processingToolBox = QtWidgets.QToolBox(self.tab_process)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.processingToolBox.setFont(font)
        self.processingToolBox.setObjectName("processingToolBox")
        self.tool_preprocess = QtWidgets.QWidget()
        self.tool_preprocess.setGeometry(QtCore.QRect(0, 0, 547, 255))
        self.tool_preprocess.setObjectName("tool_preprocess")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tool_preprocess)
        self.verticalLayout_16.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_16.setSpacing(6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.camcorGroupBox = QtWidgets.QGroupBox(self.tool_preprocess)
        self.camcorGroupBox.setStyleSheet("QGroupBox{font-size: 14px} QGroupBox::title{subcontrol-position: top left}")
        self.camcorGroupBox.setObjectName("camcorGroupBox")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.camcorGroupBox)
        self.horizontalLayout_9.setContentsMargins(8, 8, 11, 8)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.camcorCheckBox = QtWidgets.QCheckBox(self.camcorGroupBox)
        self.camcorCheckBox.setObjectName("camcorCheckBox")
        self.horizontalLayout_9.addWidget(self.camcorCheckBox)
        self.camcorTargetCombo = QtWidgets.QComboBox(self.camcorGroupBox)
        self.camcorTargetCombo.setEnabled(False)
        self.camcorTargetCombo.setObjectName("camcorTargetCombo")
        self.camcorTargetCombo.addItem("")
        self.camcorTargetCombo.addItem("")
        self.camcorTargetCombo.addItem("")
        self.horizontalLayout_9.addWidget(self.camcorTargetCombo)
        self.medianFilterCheckBox = QtWidgets.QCheckBox(self.camcorGroupBox)
        self.medianFilterCheckBox.setMouseTracking(True)
        self.medianFilterCheckBox.setObjectName("medianFilterCheckBox")
        self.horizontalLayout_9.addWidget(self.medianFilterCheckBox)
        self.saveCamCorrectedCheckBox = QtWidgets.QCheckBox(self.camcorGroupBox)
        self.saveCamCorrectedCheckBox.setEnabled(True)
        self.saveCamCorrectedCheckBox.setChecked(True)
        self.saveCamCorrectedCheckBox.setObjectName("saveCamCorrectedCheckBox")
        self.horizontalLayout_9.addWidget(self.saveCamCorrectedCheckBox)
        self.verticalLayout_16.addWidget(self.camcorGroupBox)
        self.trimEdgesGroupBox = QtWidgets.QGroupBox(self.tool_preprocess)
        self.trimEdgesGroupBox.setStyleSheet("QGroupBox{font-size: 14px} QGroupBox::title{subcontrol-position: top left}")
        self.trimEdgesGroupBox.setObjectName("trimEdgesGroupBox")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.trimEdgesGroupBox)
        self.gridLayout_23.setContentsMargins(8, 8, 11, 8)
        self.gridLayout_23.setSpacing(6)
        self.gridLayout_23.setObjectName("gridLayout_23")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem, 0, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem1, 1, 5, 1, 1)
        self.trimY0SpinBox = QtWidgets.QSpinBox(self.trimEdgesGroupBox)
        self.trimY0SpinBox.setObjectName("trimY0SpinBox")
        self.gridLayout_23.addWidget(self.trimY0SpinBox, 0, 4, 1, 1)
        self.trimX1Label = QtWidgets.QLabel(self.trimEdgesGroupBox)
        self.trimX1Label.setObjectName("trimX1Label")
        self.gridLayout_23.addWidget(self.trimX1Label, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.trimZ1SpinBox = QtWidgets.QSpinBox(self.trimEdgesGroupBox)
        self.trimZ1SpinBox.setObjectName("trimZ1SpinBox")
        self.gridLayout_23.addWidget(self.trimZ1SpinBox, 1, 7, 1, 1)
        self.trimX1SpinBox = QtWidgets.QSpinBox(self.trimEdgesGroupBox)
        self.trimX1SpinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.trimX1SpinBox.setProperty("value", 1)
        self.trimX1SpinBox.setObjectName("trimX1SpinBox")
        self.gridLayout_23.addWidget(self.trimX1SpinBox, 1, 1, 1, 1)
        self.trimY1SpinBox = QtWidgets.QSpinBox(self.trimEdgesGroupBox)
        self.trimY1SpinBox.setObjectName("trimY1SpinBox")
        self.gridLayout_23.addWidget(self.trimY1SpinBox, 1, 4, 1, 1)
        self.trimZ0Label = QtWidgets.QLabel(self.trimEdgesGroupBox)
        self.trimZ0Label.setObjectName("trimZ0Label")
        self.gridLayout_23.addWidget(self.trimZ0Label, 0, 6, 1, 1, QtCore.Qt.AlignRight)
        self.trimX0SpinBox = QtWidgets.QSpinBox(self.trimEdgesGroupBox)
        self.trimX0SpinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.trimX0SpinBox.setAutoFillBackground(False)
        self.trimX0SpinBox.setProperty("value", 1)
        self.trimX0SpinBox.setObjectName("trimX0SpinBox")
        self.gridLayout_23.addWidget(self.trimX0SpinBox, 0, 1, 1, 1)
        self.trimZ0SpinBox = QtWidgets.QSpinBox(self.trimEdgesGroupBox)
        self.trimZ0SpinBox.setAutoFillBackground(False)
        self.trimZ0SpinBox.setProperty("value", 1)
        self.trimZ0SpinBox.setObjectName("trimZ0SpinBox")
        self.gridLayout_23.addWidget(self.trimZ0SpinBox, 0, 7, 1, 1)
        self.trimY0Label = QtWidgets.QLabel(self.trimEdgesGroupBox)
        self.trimY0Label.setObjectName("trimY0Label")
        self.gridLayout_23.addWidget(self.trimY0Label, 0, 3, 1, 1, QtCore.Qt.AlignRight)
        self.trimZ1Label = QtWidgets.QLabel(self.trimEdgesGroupBox)
        self.trimZ1Label.setObjectName("trimZ1Label")
        self.gridLayout_23.addWidget(self.trimZ1Label, 1, 6, 1, 1, QtCore.Qt.AlignRight)
        self.trimX0Label = QtWidgets.QLabel(self.trimEdgesGroupBox)
        self.trimX0Label.setObjectName("trimX0Label")
        self.gridLayout_23.addWidget(self.trimX0Label, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.trimY1Label = QtWidgets.QLabel(self.trimEdgesGroupBox)
        self.trimY1Label.setObjectName("trimY1Label")
        self.gridLayout_23.addWidget(self.trimY1Label, 1, 3, 1, 1, QtCore.Qt.AlignRight)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem3, 0, 2, 1, 1)
        self.trimX0Label.raise_()
        self.trimX0SpinBox.raise_()
        self.trimY0Label.raise_()
        self.trimY0SpinBox.raise_()
        self.trimZ0Label.raise_()
        self.trimZ0SpinBox.raise_()
        self.trimX1Label.raise_()
        self.trimX1SpinBox.raise_()
        self.trimY1SpinBox.raise_()
        self.trimY1Label.raise_()
        self.trimZ1SpinBox.raise_()
        self.trimZ1Label.raise_()
        self.verticalLayout_16.addWidget(self.trimEdgesGroupBox)
        self.backgroundGroupBox = QtWidgets.QGroupBox(self.tool_preprocess)
        self.backgroundGroupBox.setStyleSheet("QGroupBox{font-size: 14px} QGroupBox::title{subcontrol-position: top left}")
        self.backgroundGroupBox.setObjectName("backgroundGroupBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.backgroundGroupBox)
        self.horizontalLayout_6.setContentsMargins(8, 8, 11, 8)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.backgroundAutoRadio = QtWidgets.QRadioButton(self.backgroundGroupBox)
        self.backgroundAutoRadio.setChecked(True)
        self.backgroundAutoRadio.setObjectName("backgroundAutoRadio")
        self.horizontalLayout_6.addWidget(self.backgroundAutoRadio)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.backgroundFixedRadio = QtWidgets.QRadioButton(self.backgroundGroupBox)
        self.backgroundFixedRadio.setObjectName("backgroundFixedRadio")
        self.horizontalLayout_6.addWidget(self.backgroundFixedRadio)
        self.backgroundFixedSpinBox = QtWidgets.QSpinBox(self.backgroundGroupBox)
        self.backgroundFixedSpinBox.setEnabled(False)
        self.backgroundFixedSpinBox.setAutoFillBackground(False)
        self.backgroundFixedSpinBox.setMaximum(1000)
        self.backgroundFixedSpinBox.setProperty("value", 90)
        self.backgroundFixedSpinBox.setObjectName("backgroundFixedSpinBox")
        self.horizontalLayout_6.addWidget(self.backgroundFixedSpinBox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.backgroundRollingRadio = QtWidgets.QRadioButton(self.backgroundGroupBox)
        self.backgroundRollingRadio.setEnabled(False)
        self.backgroundRollingRadio.setObjectName("backgroundRollingRadio")
        self.horizontalLayout_6.addWidget(self.backgroundRollingRadio)
        self.backgroundRollingSpinBox = QtWidgets.QSpinBox(self.backgroundGroupBox)
        self.backgroundRollingSpinBox.setEnabled(False)
        self.backgroundRollingSpinBox.setProperty("value", 10)
        self.backgroundRollingSpinBox.setObjectName("backgroundRollingSpinBox")
        self.horizontalLayout_6.addWidget(self.backgroundRollingSpinBox)
        self.verticalLayout_16.addWidget(self.backgroundGroupBox)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem6)
        self.processingToolBox.addItem(self.tool_preprocess, "")
        self.tool_deconvolution = QtWidgets.QWidget()
        self.tool_deconvolution.setGeometry(QtCore.QRect(0, 0, 547, 255))
        self.tool_deconvolution.setObjectName("tool_deconvolution")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tool_deconvolution)
        self.verticalLayout_14.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_14.setSpacing(6)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.doDeconGroupBox = QtWidgets.QGroupBox(self.tool_deconvolution)
        self.doDeconGroupBox.setStyleSheet("QGroupBox{font-size: 14px} QGroupBox::title{subcontrol-position: top left}")
        self.doDeconGroupBox.setFlat(False)
        self.doDeconGroupBox.setCheckable(True)
        self.doDeconGroupBox.setChecked(True)
        self.doDeconGroupBox.setObjectName("doDeconGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.doDeconGroupBox)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.deconParamsLayout = QtWidgets.QHBoxLayout()
        self.deconParamsLayout.setContentsMargins(11, 0, 11, 11)
        self.deconParamsLayout.setSpacing(6)
        self.deconParamsLayout.setObjectName("deconParamsLayout")
        self.iterationsLabel = QtWidgets.QLabel(self.doDeconGroupBox)
        self.iterationsLabel.setEnabled(True)
        self.iterationsLabel.setObjectName("iterationsLabel")
        self.deconParamsLayout.addWidget(self.iterationsLabel)
        self.iterationsSpinBox = QtWidgets.QSpinBox(self.doDeconGroupBox)
        self.iterationsSpinBox.setEnabled(True)
        self.iterationsSpinBox.setMaximum(20)
        self.iterationsSpinBox.setProperty("value", 10)
        self.iterationsSpinBox.setObjectName("iterationsSpinBox")
        self.deconParamsLayout.addWidget(self.iterationsSpinBox)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.deconParamsLayout.addItem(spacerItem7)
        self.apodizeLabel = QtWidgets.QLabel(self.doDeconGroupBox)
        self.apodizeLabel.setEnabled(True)
        self.apodizeLabel.setObjectName("apodizeLabel")
        self.deconParamsLayout.addWidget(self.apodizeLabel)
        self.apodizeSpinBox = QtWidgets.QSpinBox(self.doDeconGroupBox)
        self.apodizeSpinBox.setEnabled(True)
        self.apodizeSpinBox.setMaximum(40)
        self.apodizeSpinBox.setProperty("value", 15)
        self.apodizeSpinBox.setObjectName("apodizeSpinBox")
        self.deconParamsLayout.addWidget(self.apodizeSpinBox)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.deconParamsLayout.addItem(spacerItem8)
        self.zblendLabel = QtWidgets.QLabel(self.doDeconGroupBox)
        self.zblendLabel.setEnabled(True)
        self.zblendLabel.setObjectName("zblendLabel")
        self.deconParamsLayout.addWidget(self.zblendLabel)
        self.zblendSpinBox = QtWidgets.QSpinBox(self.doDeconGroupBox)
        self.zblendSpinBox.setEnabled(True)
        self.zblendSpinBox.setMaximum(20)
        self.zblendSpinBox.setObjectName("zblendSpinBox")
        self.deconParamsLayout.addWidget(self.zblendSpinBox)
        self.verticalLayout.addLayout(self.deconParamsLayout)
        self.deconvSaveLayout = QtWidgets.QHBoxLayout()
        self.deconvSaveLayout.setContentsMargins(11, 0, 11, 11)
        self.deconvSaveLayout.setSpacing(6)
        self.deconvSaveLayout.setObjectName("deconvSaveLayout")
        self.saveDeconvolvedCheckBox = QtWidgets.QCheckBox(self.doDeconGroupBox)
        self.saveDeconvolvedCheckBox.setEnabled(False)
        self.saveDeconvolvedCheckBox.setChecked(True)
        self.saveDeconvolvedCheckBox.setObjectName("saveDeconvolvedCheckBox")
        self.deconvSaveLayout.addWidget(self.saveDeconvolvedCheckBox)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.deconvSaveLayout.addItem(spacerItem9)
        self.deconvolvedMIPFrame = QtWidgets.QFrame(self.doDeconGroupBox)
        self.deconvolvedMIPFrame.setEnabled(True)
        self.deconvolvedMIPFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.deconvolvedMIPFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.deconvolvedMIPFrame.setObjectName("deconvolvedMIPFrame")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.deconvolvedMIPFrame)
        self.horizontalLayout_25.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_25.setSpacing(6)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.deconSaveMIPSLabel = QtWidgets.QLabel(self.deconvolvedMIPFrame)
        self.deconSaveMIPSLabel.setEnabled(True)
        self.deconSaveMIPSLabel.setObjectName("deconSaveMIPSLabel")
        self.horizontalLayout_25.addWidget(self.deconSaveMIPSLabel)
        self.deconXMIPCheckBox = QtWidgets.QCheckBox(self.deconvolvedMIPFrame)
        self.deconXMIPCheckBox.setEnabled(True)
        self.deconXMIPCheckBox.setObjectName("deconXMIPCheckBox")
        self.horizontalLayout_25.addWidget(self.deconXMIPCheckBox)
        self.deconYMIPCheckBox = QtWidgets.QCheckBox(self.deconvolvedMIPFrame)
        self.deconYMIPCheckBox.setEnabled(True)
        self.deconYMIPCheckBox.setObjectName("deconYMIPCheckBox")
        self.horizontalLayout_25.addWidget(self.deconYMIPCheckBox)
        self.deconZMIPCheckBox = QtWidgets.QCheckBox(self.deconvolvedMIPFrame)
        self.deconZMIPCheckBox.setEnabled(True)
        self.deconZMIPCheckBox.setChecked(True)
        self.deconZMIPCheckBox.setObjectName("deconZMIPCheckBox")
        self.horizontalLayout_25.addWidget(self.deconZMIPCheckBox)
        self.deconvSaveLayout.addWidget(self.deconvolvedMIPFrame)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.deconvSaveLayout.addItem(spacerItem10)
        self.deconvolvedBitDepthCombo = QtWidgets.QComboBox(self.doDeconGroupBox)
        self.deconvolvedBitDepthCombo.setEnabled(True)
        self.deconvolvedBitDepthCombo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.deconvolvedBitDepthCombo.setObjectName("deconvolvedBitDepthCombo")
        self.deconvolvedBitDepthCombo.addItem("")
        self.deconvolvedBitDepthCombo.addItem("")
        self.deconvSaveLayout.addWidget(self.deconvolvedBitDepthCombo)
        self.verticalLayout.addLayout(self.deconvSaveLayout)
        self.verticalLayout_14.addWidget(self.doDeconGroupBox)
        self.deskewedGroupBox = QtWidgets.QGroupBox(self.tool_deconvolution)
        self.deskewedGroupBox.setStyleSheet("QGroupBox{font-size: 14px} QGroupBox::title{subcontrol-position: top left}")
        self.deskewedGroupBox.setObjectName("deskewedGroupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.deskewedGroupBox)
        self.gridLayout_7.setContentsMargins(4, 4, 8, 8)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem11, 0, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem12, 0, 3, 1, 1)
        self.deskewedMIPFrame = QtWidgets.QFrame(self.deskewedGroupBox)
        self.deskewedMIPFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.deskewedMIPFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.deskewedMIPFrame.setObjectName("deskewedMIPFrame")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.deskewedMIPFrame)
        self.horizontalLayout_21.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_21.setSpacing(6)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.deconSaveMIPSLabel_2 = QtWidgets.QLabel(self.deskewedMIPFrame)
        self.deconSaveMIPSLabel_2.setEnabled(True)
        self.deconSaveMIPSLabel_2.setObjectName("deconSaveMIPSLabel_2")
        self.horizontalLayout_21.addWidget(self.deconSaveMIPSLabel_2)
        self.deskewedXMIPCheckBox = QtWidgets.QCheckBox(self.deskewedMIPFrame)
        self.deskewedXMIPCheckBox.setObjectName("deskewedXMIPCheckBox")
        self.horizontalLayout_21.addWidget(self.deskewedXMIPCheckBox)
        self.deskewedYMIPCheckBox = QtWidgets.QCheckBox(self.deskewedMIPFrame)
        self.deskewedYMIPCheckBox.setObjectName("deskewedYMIPCheckBox")
        self.horizontalLayout_21.addWidget(self.deskewedYMIPCheckBox)
        self.deskewedZMIPCheckBox = QtWidgets.QCheckBox(self.deskewedMIPFrame)
        self.deskewedZMIPCheckBox.setObjectName("deskewedZMIPCheckBox")
        self.horizontalLayout_21.addWidget(self.deskewedZMIPCheckBox)
        self.gridLayout_7.addWidget(self.deskewedMIPFrame, 0, 2, 1, 1)
        self.saveDeskewedCheckBox = QtWidgets.QCheckBox(self.deskewedGroupBox)
        self.saveDeskewedCheckBox.setChecked(True)
        self.saveDeskewedCheckBox.setObjectName("saveDeskewedCheckBox")
        self.gridLayout_7.addWidget(self.saveDeskewedCheckBox, 0, 0, 1, 1)
        self.deskewedBitDepthCombo = QtWidgets.QComboBox(self.deskewedGroupBox)
        self.deskewedBitDepthCombo.setEnabled(False)
        self.deskewedBitDepthCombo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.deskewedBitDepthCombo.setObjectName("deskewedBitDepthCombo")
        self.deskewedBitDepthCombo.addItem("")
        self.deskewedBitDepthCombo.addItem("")
        self.gridLayout_7.addWidget(self.deskewedBitDepthCombo, 0, 4, 1, 1)
        self.verticalLayout_14.addWidget(self.deskewedGroupBox)
        self.deconJoinMIPCheckBox = QtWidgets.QCheckBox(self.tool_deconvolution)
        self.deconJoinMIPCheckBox.setEnabled(True)
        self.deconJoinMIPCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.deconJoinMIPCheckBox.setChecked(True)
        self.deconJoinMIPCheckBox.setObjectName("deconJoinMIPCheckBox")
        self.verticalLayout_14.addWidget(self.deconJoinMIPCheckBox)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem13)
        self.processingToolBox.addItem(self.tool_deconvolution, "")
        self.tool_postprocess = QtWidgets.QWidget()
        self.tool_postprocess.setGeometry(QtCore.QRect(0, 0, 541, 288))
        self.tool_postprocess.setObjectName("tool_postprocess")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tool_postprocess)
        self.verticalLayout_12.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.croppingGroupBox = QtWidgets.QGroupBox(self.tool_postprocess)
        self.croppingGroupBox.setStyleSheet("QGroupBox{font-size: 14px} QGroupBox::title{subcontrol-position: top left}")
        self.croppingGroupBox.setObjectName("croppingGroupBox")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.croppingGroupBox)
        self.horizontalLayout_7.setContentsMargins(8, 5, 11, 5)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cropNoneRadio = QtWidgets.QRadioButton(self.croppingGroupBox)
        self.cropNoneRadio.setChecked(False)
        self.cropNoneRadio.setObjectName("cropNoneRadio")
        self.horizontalLayout_7.addWidget(self.cropNoneRadio)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem14)
        self.cropAutoRadio = QtWidgets.QRadioButton(self.croppingGroupBox)
        self.cropAutoRadio.setChecked(True)
        self.cropAutoRadio.setObjectName("cropAutoRadio")
        self.horizontalLayout_7.addWidget(self.cropAutoRadio)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem15)
        self.cropManualRadio = QtWidgets.QRadioButton(self.croppingGroupBox)
        self.cropManualRadio.setObjectName("cropManualRadio")
        self.horizontalLayout_7.addWidget(self.cropManualRadio)
        self.cropManualGroupBox = QtWidgets.QGroupBox(self.croppingGroupBox)
        self.cropManualGroupBox.setEnabled(True)
        self.cropManualGroupBox.setTitle("")
        self.cropManualGroupBox.setFlat(False)
        self.cropManualGroupBox.setObjectName("cropManualGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.cropManualGroupBox)
        self.horizontalLayout.setContentsMargins(4, 2, 2, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cropWidthLabel = QtWidgets.QLabel(self.cropManualGroupBox)
        self.cropWidthLabel.setEnabled(False)
        self.cropWidthLabel.setScaledContents(False)
        self.cropWidthLabel.setObjectName("cropWidthLabel")
        self.horizontalLayout.addWidget(self.cropWidthLabel)
        self.cropWidthSpinBox = QtWidgets.QSpinBox(self.cropManualGroupBox)
        self.cropWidthSpinBox.setEnabled(False)
        self.cropWidthSpinBox.setMaximum(2000)
        self.cropWidthSpinBox.setObjectName("cropWidthSpinBox")
        self.horizontalLayout.addWidget(self.cropWidthSpinBox)
        self.cropShiftLabel = QtWidgets.QLabel(self.cropManualGroupBox)
        self.cropShiftLabel.setEnabled(False)
        self.cropShiftLabel.setObjectName("cropShiftLabel")
        self.horizontalLayout.addWidget(self.cropShiftLabel)
        self.cropShiftSpinBox = QtWidgets.QSpinBox(self.cropManualGroupBox)
        self.cropShiftSpinBox.setEnabled(False)
        self.cropShiftSpinBox.setMinimum(-300)
        self.cropShiftSpinBox.setMaximum(300)
        self.cropShiftSpinBox.setObjectName("cropShiftSpinBox")
        self.horizontalLayout.addWidget(self.cropShiftSpinBox)
        self.horizontalLayout_7.addWidget(self.cropManualGroupBox)
        self.verticalLayout_12.addWidget(self.croppingGroupBox)
        self.rotateGroupBox = QtWidgets.QGroupBox(self.tool_postprocess)
        self.rotateGroupBox.setEnabled(True)
        self.rotateGroupBox.setStyleSheet("QGroupBox{font-size: 14px} QGroupBox::title{subcontrol-position: top left}")
        self.rotateGroupBox.setCheckable(True)
        self.rotateGroupBox.setChecked(True)
        self.rotateGroupBox.setObjectName("rotateGroupBox")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.rotateGroupBox)
        self.horizontalLayout_8.setContentsMargins(8, 4, 8, 4)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.rotateReverseCheckBox = QtWidgets.QCheckBox(self.rotateGroupBox)
        self.rotateReverseCheckBox.setEnabled(True)
        self.rotateReverseCheckBox.setObjectName("rotateReverseCheckBox")
        self.horizontalLayout_8.addWidget(self.rotateReverseCheckBox)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem16)
        self.rotateCropCheckBox = QtWidgets.QCheckBox(self.rotateGroupBox)
        self.rotateCropCheckBox.setEnabled(False)
        self.rotateCropCheckBox.setObjectName("rotateCropCheckBox")
        self.horizontalLayout_8.addWidget(self.rotateCropCheckBox)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem17)
        self.rotateOverrideCheckBox = QtWidgets.QCheckBox(self.rotateGroupBox)
        self.rotateOverrideCheckBox.setEnabled(True)
        self.rotateOverrideCheckBox.setObjectName("rotateOverrideCheckBox")
        self.horizontalLayout_8.addWidget(self.rotateOverrideCheckBox, 0, QtCore.Qt.AlignRight)
        self.rotateOverrideSpinBox = QtWidgets.QDoubleSpinBox(self.rotateGroupBox)
        self.rotateOverrideSpinBox.setEnabled(False)
        self.rotateOverrideSpinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.rotateOverrideSpinBox.setMinimum(-180.0)
        self.rotateOverrideSpinBox.setMaximum(180.0)
        self.rotateOverrideSpinBox.setSingleStep(0.5)
        self.rotateOverrideSpinBox.setProperty("value", 31.5)
        self.rotateOverrideSpinBox.setObjectName("rotateOverrideSpinBox")
        self.horizontalLayout_8.addWidget(self.rotateOverrideSpinBox)
        self.verticalLayout_12.addWidget(self.rotateGroupBox)
        self.doRegistrationGroupBox = QtWidgets.QGroupBox(self.tool_postprocess)
        self.doRegistrationGroupBox.setStyleSheet("QGroupBox{font-size: 14px} QGroupBox::title{subcontrol-position: top left}")
        self.doRegistrationGroupBox.setCheckable(True)
        self.doRegistrationGroupBox.setChecked(True)
        self.doRegistrationGroupBox.setObjectName("doRegistrationGroupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.doRegistrationGroupBox)
        self.verticalLayout_6.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 0, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.channelRefLabel = QtWidgets.QLabel(self.doRegistrationGroupBox)
        self.channelRefLabel.setEnabled(True)
        self.channelRefLabel.setObjectName("channelRefLabel")
        self.horizontalLayout_3.addWidget(self.channelRefLabel)
        self.channelRefCombo = QtWidgets.QComboBox(self.doRegistrationGroupBox)
        self.channelRefCombo.setEnabled(True)
        self.channelRefCombo.setMaximumSize(QtCore.QSize(70, 16777215))
        self.channelRefCombo.setObjectName("channelRefCombo")
        self.channelRefCombo.addItem("")
        self.channelRefCombo.addItem("")
        self.channelRefCombo.addItem("")
        self.channelRefCombo.addItem("")
        self.channelRefCombo.addItem("")
        self.horizontalLayout_3.addWidget(self.channelRefCombo)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem18)
        self.channelRefModeLabel = QtWidgets.QLabel(self.doRegistrationGroupBox)
        self.channelRefModeLabel.setObjectName("channelRefModeLabel")
        self.horizontalLayout_3.addWidget(self.channelRefModeLabel, 0, QtCore.Qt.AlignRight)
        self.channelRefModeCombo = QtWidgets.QComboBox(self.doRegistrationGroupBox)
        self.channelRefModeCombo.setEnabled(True)
        self.channelRefModeCombo.setMinimumSize(QtCore.QSize(200, 0))
        self.channelRefModeCombo.setMaximumSize(QtCore.QSize(70, 16777215))
        self.channelRefModeCombo.setObjectName("channelRefModeCombo")
        self.channelRefModeCombo.addItem("")
        self.channelRefModeCombo.addItem("")
        self.channelRefModeCombo.addItem("")
        self.channelRefModeCombo.addItem("")
        self.channelRefModeCombo.addItem("")
        self.channelRefModeCombo.addItem("")
        self.channelRefModeCombo.addItem("")
        self.channelRefModeCombo.addItem("")
        self.channelRefModeCombo.addItem("")
        self.horizontalLayout_3.addWidget(self.channelRefModeCombo)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 0, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.RegCalibPathLabel = QtWidgets.QLabel(self.doRegistrationGroupBox)
        self.RegCalibPathLabel.setObjectName("RegCalibPathLabel")
        self.horizontalLayout_2.addWidget(self.RegCalibPathLabel)
        self.RegCalibPathLineEdit = QtWidgets.QLineEdit(self.doRegistrationGroupBox)
        self.RegCalibPathLineEdit.setEnabled(True)
        self.RegCalibPathLineEdit.setObjectName("RegCalibPathLineEdit")
        self.horizontalLayout_2.addWidget(self.RegCalibPathLineEdit)
        self.RegCalibPathToolButton = QtWidgets.QToolButton(self.doRegistrationGroupBox)
        self.RegCalibPathToolButton.setObjectName("RegCalibPathToolButton")
        self.horizontalLayout_2.addWidget(self.RegCalibPathToolButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_12.addWidget(self.doRegistrationGroupBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 0, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bleachCorrectionCheckBox = QtWidgets.QCheckBox(self.tool_postprocess)
        self.bleachCorrectionCheckBox.setObjectName("bleachCorrectionCheckBox")
        self.horizontalLayout_4.addWidget(self.bleachCorrectionCheckBox)
        self.compressRawCheckBox = QtWidgets.QCheckBox(self.tool_postprocess)
        self.compressRawCheckBox.setObjectName("compressRawCheckBox")
        self.horizontalLayout_4.addWidget(self.compressRawCheckBox)
        self.verticalLayout_12.addLayout(self.horizontalLayout_4)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem19)
        self.processingToolBox.addItem(self.tool_postprocess, "")
        self.process_tab_layout.addWidget(self.processingToolBox)
        self.tabWidget.addTab(self.tab_process, "")
        self.tab_config = QtWidgets.QWidget()
        self.tab_config.setObjectName("tab_config")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_config)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.cudaDeconvPathLabel = QtWidgets.QLabel(self.tab_config)
        self.cudaDeconvPathLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cudaDeconvPathLabel.setObjectName("cudaDeconvPathLabel")
        self.gridLayout.addWidget(self.cudaDeconvPathLabel, 1, 0, 1, 1)
        self.cudaDeconvPathLineEdit = QtWidgets.QLineEdit(self.tab_config)
        self.cudaDeconvPathLineEdit.setObjectName("cudaDeconvPathLineEdit")
        self.gridLayout.addWidget(self.cudaDeconvPathLineEdit, 1, 2, 1, 1)
        self.camParamTiffLineEdit = QtWidgets.QLineEdit(self.tab_config)
        self.camParamTiffLineEdit.setText("")
        self.camParamTiffLineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.camParamTiffLineEdit.setObjectName("camParamTiffLineEdit")
        self.gridLayout.addWidget(self.camParamTiffLineEdit, 3, 2, 1, 1)
        self.camParamTiffToolButton = QtWidgets.QToolButton(self.tab_config)
        self.camParamTiffToolButton.setObjectName("camParamTiffToolButton")
        self.gridLayout.addWidget(self.camParamTiffToolButton, 3, 6, 1, 1)
        self.defaultRegCalibPathLabel = QtWidgets.QLabel(self.tab_config)
        self.defaultRegCalibPathLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.defaultRegCalibPathLabel.setObjectName("defaultRegCalibPathLabel")
        self.gridLayout.addWidget(self.defaultRegCalibPathLabel, 4, 0, 1, 1)
        self.defaultRegCalibPathLineEdit = QtWidgets.QLineEdit(self.tab_config)
        self.defaultRegCalibPathLineEdit.setText("")
        self.defaultRegCalibPathLineEdit.setObjectName("defaultRegCalibPathLineEdit")
        self.gridLayout.addWidget(self.defaultRegCalibPathLineEdit, 4, 2, 1, 1)
        self.otfFolderPathLabel = QtWidgets.QLabel(self.tab_config)
        self.otfFolderPathLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.otfFolderPathLabel.setObjectName("otfFolderPathLabel")
        self.gridLayout.addWidget(self.otfFolderPathLabel, 2, 0, 1, 1)
        self.defaultRegCalibPathToolButton = QtWidgets.QToolButton(self.tab_config)
        self.defaultRegCalibPathToolButton.setObjectName("defaultRegCalibPathToolButton")
        self.gridLayout.addWidget(self.defaultRegCalibPathToolButton, 4, 6, 1, 1)
        self.watchDirLineEdit = QtWidgets.QLineEdit(self.tab_config)
        self.watchDirLineEdit.setEnabled(False)
        self.watchDirLineEdit.setText("")
        self.watchDirLineEdit.setReadOnly(True)
        self.watchDirLineEdit.setObjectName("watchDirLineEdit")
        self.gridLayout.addWidget(self.watchDirLineEdit, 6, 2, 1, 1)
        self.watchDirToolButton = QtWidgets.QToolButton(self.tab_config)
        self.watchDirToolButton.setEnabled(False)
        self.watchDirToolButton.setObjectName("watchDirToolButton")
        self.gridLayout.addWidget(self.watchDirToolButton, 6, 6, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 600, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem20, 5, 2, 1, 1)
        self.watchDirCheckBox = QtWidgets.QCheckBox(self.tab_config)
        self.watchDirCheckBox.setObjectName("watchDirCheckBox")
        self.gridLayout.addWidget(self.watchDirCheckBox, 6, 0, 1, 1)
        self.otfFolderLineEdit = QtWidgets.QLineEdit(self.tab_config)
        self.otfFolderLineEdit.setText("")
        self.otfFolderLineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.otfFolderLineEdit.setObjectName("otfFolderLineEdit")
        self.gridLayout.addWidget(self.otfFolderLineEdit, 2, 2, 1, 1)
        self.useBundledBinariesCheckBox = QtWidgets.QCheckBox(self.tab_config)
        self.useBundledBinariesCheckBox.setChecked(False)
        self.useBundledBinariesCheckBox.setObjectName("useBundledBinariesCheckBox")
        self.gridLayout.addWidget(self.useBundledBinariesCheckBox, 0, 2, 1, 1)
        self.otfFolderToolButton = QtWidgets.QToolButton(self.tab_config)
        self.otfFolderToolButton.setObjectName("otfFolderToolButton")
        self.gridLayout.addWidget(self.otfFolderToolButton, 2, 6, 1, 1)
        self.camParamTiffLabel = QtWidgets.QLabel(self.tab_config)
        self.camParamTiffLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.camParamTiffLabel.setObjectName("camParamTiffLabel")
        self.gridLayout.addWidget(self.camParamTiffLabel, 3, 0, 1, 1)
        self.cudaDeconvPathToolButton = QtWidgets.QToolButton(self.tab_config)
        self.cudaDeconvPathToolButton.setAutoRaise(False)
        self.cudaDeconvPathToolButton.setObjectName("cudaDeconvPathToolButton")
        self.gridLayout.addWidget(self.cudaDeconvPathToolButton, 1, 6, 1, 1)
        self.tabWidget.addTab(self.tab_config, "")
        self.tab_log = QtWidgets.QWidget()
        self.tab_log.setObjectName("tab_log")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_log)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.log = QtWidgets.QTextEdit(self.tab_log)
        self.log.setAutoFillBackground(False)
        self.log.setStyleSheet("")
        self.log.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.log.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.log.setLineWidth(2)
        self.log.setReadOnly(True)
        self.log.setObjectName("log")
        self.verticalLayout_2.addWidget(self.log)
        self.tabWidget.addTab(self.tab_log, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.previewProcessButtonFrame = QtWidgets.QFrame(self.centralWidget)
        self.previewProcessButtonFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.previewProcessButtonFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.previewProcessButtonFrame.setObjectName("previewProcessButtonFrame")
        self.processButtonLayout = QtWidgets.QHBoxLayout(self.previewProcessButtonFrame)
        self.processButtonLayout.setContentsMargins(11, 0, 11, 0)
        self.processButtonLayout.setSpacing(6)
        self.processButtonLayout.setObjectName("processButtonLayout")
        self.previewButton = QtWidgets.QPushButton(self.previewProcessButtonFrame)
        self.previewButton.setEnabled(True)
        self.previewButton.setMinimumSize(QtCore.QSize(0, 0))
        self.previewButton.setAutoDefault(True)
        self.previewButton.setDefault(False)
        self.previewButton.setFlat(False)
        self.previewButton.setObjectName("previewButton")
        self.processButtonLayout.addWidget(self.previewButton)
        self.previewTRangeLineEdit = QtWidgets.QLineEdit(self.previewProcessButtonFrame)
        self.previewTRangeLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.previewTRangeLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.previewTRangeLineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.previewTRangeLineEdit.setClearButtonEnabled(False)
        self.previewTRangeLineEdit.setObjectName("previewTRangeLineEdit")
        self.processButtonLayout.addWidget(self.previewTRangeLineEdit)
        self.line = QtWidgets.QFrame(self.previewProcessButtonFrame)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.processButtonLayout.addWidget(self.line)
        self.processButton = QtWidgets.QPushButton(self.previewProcessButtonFrame)
        self.processButton.setMinimumSize(QtCore.QSize(0, 0))
        self.processButton.setObjectName("processButton")
        self.processButtonLayout.addWidget(self.processButton)
        self.processTRangeLineEdit = QtWidgets.QLineEdit(self.previewProcessButtonFrame)
        self.processTRangeLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.processTRangeLineEdit.setObjectName("processTRangeLineEdit")
        self.processButtonLayout.addWidget(self.processTRangeLineEdit)
        self.processCRangeLineEdit = QtWidgets.QLineEdit(self.previewProcessButtonFrame)
        self.processCRangeLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.processCRangeLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.processCRangeLineEdit.setObjectName("processCRangeLineEdit")
        self.processButtonLayout.addWidget(self.processCRangeLineEdit)
        self.verticalLayout_4.addWidget(self.previewProcessButtonFrame)
        self.progressLayout = QtWidgets.QHBoxLayout()
        self.progressLayout.setContentsMargins(11, 11, 11, 11)
        self.progressLayout.setSpacing(6)
        self.progressLayout.setObjectName("progressLayout")
        self.progressBar = QtWidgets.QProgressBar(self.centralWidget)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 0))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border: 1px solid grey;\n"
"    border-radius: 3px;\n"
"    height: 20px;\n"
"    margin: 0px 0px 0px 5px;\n"
"}\n"
"\n"
"QProgressBar::chunk:horizontal {\n"
"    background: qlineargradient(x1: 0, y1: 0.5, x2: 1, y2: 0.5, stop: 0 #484DE7, stop: 1 #787DFF);\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.progressLayout.addWidget(self.progressBar)
        self.clock = QtWidgets.QLCDNumber(self.centralWidget)
        self.clock.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.clock.setFont(font)
        self.clock.setStyleSheet("")
        self.clock.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.clock.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.clock.setLineWidth(1)
        self.clock.setMidLineWidth(0)
        self.clock.setSmallDecimalPoint(True)
        self.clock.setDigitCount(8)
        self.clock.setMode(QtWidgets.QLCDNumber.Dec)
        self.clock.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.clock.setObjectName("clock")
        self.progressLayout.addWidget(self.clock)
        self.verticalLayout_4.addLayout(self.progressLayout)
        Main_GUI.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Main_GUI)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 617, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        self.menuProcess = QtWidgets.QMenu(self.menuBar)
        self.menuProcess.setObjectName("menuProcess")
        Main_GUI.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(Main_GUI)
        self.mainToolBar.setEnabled(True)
        self.mainToolBar.setObjectName("mainToolBar")
        Main_GUI.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(Main_GUI)
        self.statusBar.setObjectName("statusBar")
        Main_GUI.setStatusBar(self.statusBar)
        self.actionQuit = QtWidgets.QAction(Main_GUI)
        self.actionQuit.setObjectName("actionQuit")
        self.actionPreview = QtWidgets.QAction(Main_GUI)
        self.actionPreview.setObjectName("actionPreview")
        self.actionRun = QtWidgets.QAction(Main_GUI)
        self.actionRun.setObjectName("actionRun")
        self.actionAbort = QtWidgets.QAction(Main_GUI)
        self.actionAbort.setEnabled(False)
        self.actionAbort.setObjectName("actionAbort")
        self.actionOpen_LLSdir = QtWidgets.QAction(Main_GUI)
        self.actionOpen_LLSdir.setObjectName("actionOpen_LLSdir")
        self.actionSave_Settings_as_Default = QtWidgets.QAction(Main_GUI)
        self.actionSave_Settings_as_Default.setObjectName("actionSave_Settings_as_Default")
        self.actionLoad_Default_Settings = QtWidgets.QAction(Main_GUI)
        self.actionLoad_Default_Settings.setObjectName("actionLoad_Default_Settings")
        self.actionReduce_to_Raw = QtWidgets.QAction(Main_GUI)
        self.actionReduce_to_Raw.setObjectName("actionReduce_to_Raw")
        self.actionCompress_Folder = QtWidgets.QAction(Main_GUI)
        self.actionCompress_Folder.setObjectName("actionCompress_Folder")
        self.actionDecompress_Folder = QtWidgets.QAction(Main_GUI)
        self.actionDecompress_Folder.setObjectName("actionDecompress_Folder")
        self.actionConcatenate = QtWidgets.QAction(Main_GUI)
        self.actionConcatenate.setObjectName("actionConcatenate")
        self.actionRename_Scripted = QtWidgets.QAction(Main_GUI)
        self.actionRename_Scripted.setObjectName("actionRename_Scripted")
        self.menuFile.addAction(self.actionQuit)
        self.menuFile.addAction(self.actionOpen_LLSdir)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Settings_as_Default)
        self.menuFile.addAction(self.actionLoad_Default_Settings)
        self.menuView.addSeparator()
        self.menuProcess.addAction(self.actionPreview)
        self.menuProcess.addAction(self.actionRun)
        self.menuProcess.addAction(self.actionAbort)
        self.menuProcess.addSeparator()
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuProcess.menuAction())
        self.mainToolBar.addAction(self.actionReduce_to_Raw)
        self.mainToolBar.addAction(self.actionCompress_Folder)
        self.mainToolBar.addAction(self.actionDecompress_Folder)
        self.mainToolBar.addAction(self.actionConcatenate)
        self.mainToolBar.addAction(self.actionRename_Scripted)
        self.cudaDeconvPathLabel.setBuddy(self.cudaDeconvPathLineEdit)
        self.defaultRegCalibPathLabel.setBuddy(self.defaultRegCalibPathLineEdit)
        self.otfFolderPathLabel.setBuddy(self.otfFolderLineEdit)
        self.camParamTiffLabel.setBuddy(self.camParamTiffLineEdit)

        self.retranslateUi(Main_GUI)
        self.tabWidget.setCurrentIndex(0)
        self.processingToolBox.setCurrentIndex(1)
        self.actionQuit.triggered['bool'].connect(Main_GUI.close)
        self.backgroundRollingRadio.toggled['bool'].connect(self.backgroundRollingSpinBox.setEnabled)
        self.backgroundFixedRadio.toggled['bool'].connect(self.backgroundFixedSpinBox.setEnabled)
        self.cropManualRadio.toggled['bool'].connect(self.cropWidthSpinBox.setEnabled)
        self.cropManualRadio.toggled['bool'].connect(self.cropShiftSpinBox.setEnabled)
        self.cropManualRadio.toggled['bool'].connect(self.cropWidthLabel.setEnabled)
        self.cropManualRadio.toggled['bool'].connect(self.cropShiftLabel.setEnabled)
        self.rotateOverrideCheckBox.toggled['bool'].connect(self.rotateOverrideSpinBox.setEnabled)
        self.camcorCheckBox.toggled['bool'].connect(self.camcorTargetCombo.setEnabled)
        self.watchDirCheckBox.toggled['bool'].connect(self.watchDirToolButton.setEnabled)
        self.watchDirCheckBox.toggled['bool'].connect(self.watchDirLineEdit.setEnabled)
        self.useBundledBinariesCheckBox.toggled['bool'].connect(self.cudaDeconvPathLineEdit.setHidden)
        self.useBundledBinariesCheckBox.toggled['bool'].connect(self.cudaDeconvPathLabel.setHidden)
        self.useBundledBinariesCheckBox.toggled['bool'].connect(self.cudaDeconvPathToolButton.setHidden)
        QtCore.QMetaObject.connectSlotsByName(Main_GUI)

    def retranslateUi(self, Main_GUI):
        _translate = QtCore.QCoreApplication.translate
        Main_GUI.setWindowTitle(_translate("Main_GUI", "Main_GUI"))
        item = self.listbox.horizontalHeaderItem(0)
        item.setText(_translate("Main_GUI", "basename"))
        item = self.listbox.horizontalHeaderItem(1)
        item.setText(_translate("Main_GUI", "nC"))
        item = self.listbox.horizontalHeaderItem(2)
        item.setText(_translate("Main_GUI", "nT"))
        item = self.listbox.horizontalHeaderItem(3)
        item.setText(_translate("Main_GUI", "nX"))
        item = self.listbox.horizontalHeaderItem(4)
        item.setText(_translate("Main_GUI", "nY"))
        item = self.listbox.horizontalHeaderItem(5)
        item.setText(_translate("Main_GUI", "nZ"))
        item = self.listbox.horizontalHeaderItem(6)
        item.setText(_translate("Main_GUI", "desQ"))
        self.camcorGroupBox.setTitle(_translate("Main_GUI", "Camera Correction"))
        self.camcorCheckBox.setText(_translate("Main_GUI", "Do Flash Correction"))
        self.camcorTargetCombo.setItemText(0, _translate("Main_GUI", "CPU"))
        self.camcorTargetCombo.setItemText(1, _translate("Main_GUI", "Parallel"))
        self.camcorTargetCombo.setItemText(2, _translate("Main_GUI", "CUDA"))
        self.medianFilterCheckBox.setText(_translate("Main_GUI", "Do Median Filter"))
        self.saveCamCorrectedCheckBox.setText(_translate("Main_GUI", "Save Corrected"))
        self.trimEdgesGroupBox.setTitle(_translate("Main_GUI", "Trim Edges"))
        self.trimX1Label.setText(_translate("Main_GUI", "Trim X Right"))
        self.trimZ0Label.setText(_translate("Main_GUI", "Trim Z first"))
        self.trimY0Label.setText(_translate("Main_GUI", "Trim Y Top"))
        self.trimZ1Label.setText(_translate("Main_GUI", "Trim Z last"))
        self.trimX0Label.setText(_translate("Main_GUI", "Trim X Left"))
        self.trimY1Label.setText(_translate("Main_GUI", "Trim Y Bottom"))
        self.backgroundGroupBox.setTitle(_translate("Main_GUI", "Background Subtraction"))
        self.backgroundAutoRadio.setText(_translate("Main_GUI", "Autodetect"))
        self.backgroundFixedRadio.setText(_translate("Main_GUI", "Fixed value"))
        self.backgroundRollingRadio.setText(_translate("Main_GUI", "Rolling Ball Radius:"))
        self.processingToolBox.setItemText(self.processingToolBox.indexOf(self.tool_preprocess), _translate("Main_GUI", "Pre-Processing"))
        self.doDeconGroupBox.setTitle(_translate("Main_GUI", "Do Deconvolution"))
        self.iterationsLabel.setText(_translate("Main_GUI", "Iterations:"))
        self.apodizeLabel.setText(_translate("Main_GUI", "nApodize:"))
        self.zblendLabel.setText(_translate("Main_GUI", "nZblend"))
        self.saveDeconvolvedCheckBox.setText(_translate("Main_GUI", "Save Stacks"))
        self.deconSaveMIPSLabel.setText(_translate("Main_GUI", "Save MIPs:"))
        self.deconXMIPCheckBox.setText(_translate("Main_GUI", "X"))
        self.deconYMIPCheckBox.setText(_translate("Main_GUI", "Y"))
        self.deconZMIPCheckBox.setText(_translate("Main_GUI", "Z"))
        self.deconvolvedBitDepthCombo.setCurrentText(_translate("Main_GUI", "16-bit"))
        self.deconvolvedBitDepthCombo.setItemText(0, _translate("Main_GUI", "16-bit"))
        self.deconvolvedBitDepthCombo.setItemText(1, _translate("Main_GUI", "32-bit"))
        self.deskewedGroupBox.setTitle(_translate("Main_GUI", "Raw Deskewed"))
        self.deconSaveMIPSLabel_2.setText(_translate("Main_GUI", "Save MIPs:"))
        self.deskewedXMIPCheckBox.setText(_translate("Main_GUI", "X"))
        self.deskewedYMIPCheckBox.setText(_translate("Main_GUI", "Y"))
        self.deskewedZMIPCheckBox.setText(_translate("Main_GUI", "Z"))
        self.saveDeskewedCheckBox.setText(_translate("Main_GUI", "Save Deskwed"))
        self.deskewedBitDepthCombo.setCurrentText(_translate("Main_GUI", "16-bit"))
        self.deskewedBitDepthCombo.setItemText(0, _translate("Main_GUI", "16-bit"))
        self.deskewedBitDepthCombo.setItemText(1, _translate("Main_GUI", "32-bit"))
        self.deconJoinMIPCheckBox.setText(_translate("Main_GUI", "Join MIP files into single hyperstack"))
        self.processingToolBox.setItemText(self.processingToolBox.indexOf(self.tool_deconvolution), _translate("Main_GUI", "Deskew/Deconvolution/Saving"))
        self.croppingGroupBox.setTitle(_translate("Main_GUI", "Cropping"))
        self.cropNoneRadio.setText(_translate("Main_GUI", "None"))
        self.cropAutoRadio.setText(_translate("Main_GUI", "AutoCrop"))
        self.cropManualRadio.setText(_translate("Main_GUI", "Manual"))
        self.cropWidthLabel.setText(_translate("Main_GUI", "Width:"))
        self.cropShiftLabel.setText(_translate("Main_GUI", "Shift:"))
        self.rotateGroupBox.setTitle(_translate("Main_GUI", "Rotate to coverslip coordinates"))
        self.rotateReverseCheckBox.setText(_translate("Main_GUI", "Reverse"))
        self.rotateCropCheckBox.setText(_translate("Main_GUI", "Crop"))
        self.rotateOverrideCheckBox.setText(_translate("Main_GUI", "Override angle:"))
        self.doRegistrationGroupBox.setTitle(_translate("Main_GUI", "Do Channel Registration"))
        self.channelRefLabel.setText(_translate("Main_GUI", "Reference Channel:"))
        self.channelRefCombo.setCurrentText(_translate("Main_GUI", "405"))
        self.channelRefCombo.setItemText(0, _translate("Main_GUI", "405"))
        self.channelRefCombo.setItemText(1, _translate("Main_GUI", "488"))
        self.channelRefCombo.setItemText(2, _translate("Main_GUI", "560"))
        self.channelRefCombo.setItemText(3, _translate("Main_GUI", "592"))
        self.channelRefCombo.setItemText(4, _translate("Main_GUI", "642"))
        self.channelRefModeLabel.setText(_translate("Main_GUI", "Mode:"))
        self.channelRefModeCombo.setCurrentText(_translate("Main_GUI", "Translation"))
        self.channelRefModeCombo.setItemText(0, _translate("Main_GUI", "Translation"))
        self.channelRefModeCombo.setItemText(1, _translate("Main_GUI", "Rigid"))
        self.channelRefModeCombo.setItemText(2, _translate("Main_GUI", "Similarity"))
        self.channelRefModeCombo.setItemText(3, _translate("Main_GUI", "Affine"))
        self.channelRefModeCombo.setItemText(4, _translate("Main_GUI", "2step"))
        self.channelRefModeCombo.setItemText(5, _translate("Main_GUI", "CPD_Rigid"))
        self.channelRefModeCombo.setItemText(6, _translate("Main_GUI", "CPD_Similarity"))
        self.channelRefModeCombo.setItemText(7, _translate("Main_GUI", "CPD_Affine"))
        self.channelRefModeCombo.setItemText(8, _translate("Main_GUI", "CPD_2step"))
        self.RegCalibPathLabel.setText(_translate("Main_GUI", "Calibration:"))
        self.RegCalibPathLineEdit.setPlaceholderText(_translate("Main_GUI", "Default: \"Registration\" folder in parent directory"))
        self.RegCalibPathToolButton.setText(_translate("Main_GUI", "..."))
        self.bleachCorrectionCheckBox.setText(_translate("Main_GUI", "Do Bleach Correction"))
        self.compressRawCheckBox.setText(_translate("Main_GUI", "Compress Raw Data"))
        self.processingToolBox.setItemText(self.processingToolBox.indexOf(self.tool_postprocess), _translate("Main_GUI", "Post-Processing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_process), _translate("Main_GUI", "Process"))
        self.cudaDeconvPathLabel.setText(_translate("Main_GUI", "cudaDeconv binary"))
        self.cudaDeconvPathLineEdit.setText(_translate("Main_GUI", "/usr/local/cudaDeconv"))
        self.cudaDeconvPathLineEdit.setPlaceholderText(_translate("Main_GUI", "path to cudaDeconv binary"))
        self.camParamTiffLineEdit.setPlaceholderText(_translate("Main_GUI", "path to TIFF file with measured camera parameters"))
        self.camParamTiffToolButton.setText(_translate("Main_GUI", "..."))
        self.defaultRegCalibPathLabel.setText(_translate("Main_GUI", "Default Reg Calib"))
        self.defaultRegCalibPathLineEdit.setPlaceholderText(_translate("Main_GUI", "path to default registration calibration (tetraspeck) images"))
        self.otfFolderPathLabel.setText(_translate("Main_GUI", "OTF directory"))
        self.defaultRegCalibPathToolButton.setText(_translate("Main_GUI", "..."))
        self.watchDirLineEdit.setPlaceholderText(_translate("Main_GUI", "New items in watched folder will be automatically processed."))
        self.watchDirToolButton.setText(_translate("Main_GUI", "..."))
        self.watchDirCheckBox.setText(_translate("Main_GUI", "Watch Directory:"))
        self.otfFolderLineEdit.setPlaceholderText(_translate("Main_GUI", "path to directory with PSFs/OTFs"))
        self.useBundledBinariesCheckBox.setText(_translate("Main_GUI", "Use bundled cudaDeconv binary"))
        self.otfFolderToolButton.setText(_translate("Main_GUI", "..."))
        self.camParamTiffLabel.setText(_translate("Main_GUI", "CameraParam Tiff"))
        self.cudaDeconvPathToolButton.setText(_translate("Main_GUI", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_config), _translate("Main_GUI", "Config"))
        self.log.setHtml(_translate("Main_GUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_log), _translate("Main_GUI", "Log"))
        self.previewButton.setToolTip(_translate("Main_GUI", "Preview the highlighted dataset with the current settings"))
        self.previewButton.setText(_translate("Main_GUI", "Preview"))
        self.previewTRangeLineEdit.setToolTip(_translate("Main_GUI", "<html><head/><body><p><span style=\" font-size:12pt;\">a string can be used to dictate a subset of timepoints to preview. Separate list items with commas, and &quot;start-stop-step&quot; items with dashes.<br>For instance: \'0,3,5-10,15-30-3,40\'<br>NOTE: time is zero-indexed</span></p></body></html>"))
        self.previewTRangeLineEdit.setPlaceholderText(_translate("Main_GUI", "time subset"))
        self.processButton.setText(_translate("Main_GUI", "Process"))
        self.processTRangeLineEdit.setToolTip(_translate("Main_GUI", "<html><head/><body><p><span style=\" font-size:12pt;\">a string can be used to dictate a subset of timepoints to process. Separate list items with commas, and &quot;start-stop-step&quot; items with dashes.<br>For instance: \'0,3,5-10,15-30-3,40\'<br>NOTE: time is zero-indexed</span></p></body></html>"))
        self.processTRangeLineEdit.setPlaceholderText(_translate("Main_GUI", "time subset"))
        self.processCRangeLineEdit.setToolTip(_translate("Main_GUI", "<html><head/><body><p><span style=\" font-size:12pt;\">a string can be used to dictate a subset of channels to preview. Separate list items with commas, and &quot;start-stop-step&quot; items with dashes. <br>For instance: \'0,2-3\'<br>NOTE: channels are zero-indexed</span></p></body></html>"))
        self.processCRangeLineEdit.setPlaceholderText(_translate("Main_GUI", "channel subset"))
        self.menuFile.setTitle(_translate("Main_GUI", "File"))
        self.menuView.setTitle(_translate("Main_GUI", "View"))
        self.menuProcess.setTitle(_translate("Main_GUI", "Process"))
        self.actionQuit.setText(_translate("Main_GUI", "Quit"))
        self.actionQuit.setShortcut(_translate("Main_GUI", "Ctrl+Q"))
        self.actionPreview.setText(_translate("Main_GUI", "Preview"))
        self.actionPreview.setShortcut(_translate("Main_GUI", "Ctrl+P"))
        self.actionRun.setText(_translate("Main_GUI", "Run"))
        self.actionRun.setShortcut(_translate("Main_GUI", "Ctrl+R"))
        self.actionAbort.setText(_translate("Main_GUI", "Abort"))
        self.actionAbort.setShortcut(_translate("Main_GUI", "Ctrl+X"))
        self.actionOpen_LLSdir.setText(_translate("Main_GUI", "Open LLSdir"))
        self.actionOpen_LLSdir.setShortcut(_translate("Main_GUI", "Ctrl+O"))
        self.actionSave_Settings_as_Default.setText(_translate("Main_GUI", "Save Settings as Default"))
        self.actionSave_Settings_as_Default.setShortcut(_translate("Main_GUI", "Ctrl+S"))
        self.actionLoad_Default_Settings.setText(_translate("Main_GUI", "Load Default Settings"))
        self.actionLoad_Default_Settings.setShortcut(_translate("Main_GUI", "Ctrl+D"))
        self.actionReduce_to_Raw.setText(_translate("Main_GUI", "Reduce to Raw"))
        self.actionReduce_to_Raw.setToolTip(_translate("Main_GUI", "Remove all processed data from selected folder and restore folder to it\'s original state after acquisition"))
        self.actionCompress_Folder.setText(_translate("Main_GUI", "Compress Raw"))
        self.actionCompress_Folder.setToolTip(_translate("Main_GUI", "Compress raw data in selected folder"))
        self.actionDecompress_Folder.setText(_translate("Main_GUI", "Decompress Raw"))
        self.actionConcatenate.setText(_translate("Main_GUI", "Concatenate"))
        self.actionConcatenate.setToolTip(_translate("Main_GUI", "Merge selected folders into single LLSdir"))
        self.actionRename_Scripted.setText(_translate("Main_GUI", "Rename Scripted"))
        self.actionRename_Scripted.setToolTip(_translate("Main_GUI", "Rename \"Iter_\" files in an LLSdir acquired with Script Editor"))

