# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'llspy/gui/slm_pattern_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(942, 498)
        Dialog.setMinimumSize(QtCore.QSize(942, 492))
        Dialog.setMaximumSize(QtCore.QSize(942, 4575647))
        Dialog.setStyleSheet("")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lowerLeftScroll = QtWidgets.QScrollArea(Dialog)
        self.lowerLeftScroll.setMinimumSize(QtCore.QSize(450, 150))
        self.lowerLeftScroll.setMaximumSize(QtCore.QSize(450, 150))
        self.lowerLeftScroll.setWidgetResizable(True)
        self.lowerLeftScroll.setObjectName("lowerLeftScroll")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 448, 148))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.lowerLeftScroll.setWidget(self.scrollAreaWidgetContents_5)
        self.horizontalLayout.addWidget(self.lowerLeftScroll)
        self.lowerRightScroll = QtWidgets.QScrollArea(Dialog)
        self.lowerRightScroll.setMinimumSize(QtCore.QSize(450, 150))
        self.lowerRightScroll.setMaximumSize(QtCore.QSize(450, 150))
        self.lowerRightScroll.setWidgetResizable(True)
        self.lowerRightScroll.setObjectName("lowerRightScroll")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 448, 148))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.lowerRightScroll.setWidget(self.scrollAreaWidgetContents_4)
        self.horizontalLayout.addWidget(self.lowerRightScroll)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.upperRightScroll = QtWidgets.QScrollArea(Dialog)
        self.upperRightScroll.setMinimumSize(QtCore.QSize(300, 300))
        self.upperRightScroll.setMaximumSize(QtCore.QSize(300, 300))
        self.upperRightScroll.setWidgetResizable(True)
        self.upperRightScroll.setObjectName("upperRightScroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 298, 298))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.upperRightScroll.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.upperRightScroll, 0, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.Settings = QtWidgets.QWidget()
        self.Settings.setObjectName("Settings")
        self.gridLayout = QtWidgets.QGridLayout(self.Settings)
        self.gridLayout.setContentsMargins(-1, -1, -1, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.Settings)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.spacingSpin = QtWidgets.QDoubleSpinBox(self.Settings)
        self.spacingSpin.setEnabled(False)
        self.spacingSpin.setSpecialValueText("")
        self.spacingSpin.setDecimals(3)
        self.spacingSpin.setMinimum(0.001)
        self.spacingSpin.setMaximum(40.0)
        self.spacingSpin.setSingleStep(0.001)
        self.spacingSpin.setProperty("value", 1.084)
        self.spacingSpin.setObjectName("spacingSpin")
        self.gridLayout.addWidget(self.spacingSpin, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.Settings)
        self.label_4.setEnabled(False)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 2, 1, 1)
        self.innerNASpin = QtWidgets.QDoubleSpinBox(self.Settings)
        self.innerNASpin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.innerNASpin.setSpecialValueText("")
        self.innerNASpin.setDecimals(3)
        self.innerNASpin.setMinimum(0.1)
        self.innerNASpin.setMaximum(0.64)
        self.innerNASpin.setSingleStep(0.001)
        self.innerNASpin.setProperty("value", 0.42)
        self.innerNASpin.setObjectName("innerNASpin")
        self.gridLayout.addWidget(self.innerNASpin, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.Settings)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 1)
        self.previewPatternButton = QtWidgets.QPushButton(self.Settings)
        self.previewPatternButton.setMinimumSize(QtCore.QSize(0, 40))
        self.previewPatternButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.previewPatternButton.setAutoDefault(False)
        self.previewPatternButton.setDefault(False)
        self.previewPatternButton.setFlat(False)
        self.previewPatternButton.setObjectName("previewPatternButton")
        self.gridLayout.addWidget(self.previewPatternButton, 6, 2, 1, 2)
        self.nBeamsSpin = QtWidgets.QSpinBox(self.Settings)
        self.nBeamsSpin.setSpecialValueText("")
        self.nBeamsSpin.setMinimum(1)
        self.nBeamsSpin.setMaximum(150)
        self.nBeamsSpin.setObjectName("nBeamsSpin")
        self.gridLayout.addWidget(self.nBeamsSpin, 1, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.Settings)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.Settings)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 3, 0, 1, 1)
        self.outerNASpin = QtWidgets.QDoubleSpinBox(self.Settings)
        self.outerNASpin.setMaximumSize(QtCore.QSize(70, 16777215))
        self.outerNASpin.setSpecialValueText("")
        self.outerNASpin.setDecimals(3)
        self.outerNASpin.setMinimum(0.15)
        self.outerNASpin.setMaximum(0.7)
        self.outerNASpin.setSingleStep(0.001)
        self.outerNASpin.setProperty("value", 0.5)
        self.outerNASpin.setObjectName("outerNASpin")
        self.gridLayout.addWidget(self.outerNASpin, 1, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.Settings)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 3, 1, 1)
        self.fudgeSpin = QtWidgets.QDoubleSpinBox(self.Settings)
        self.fudgeSpin.setMaximumSize(QtCore.QSize(70, 16777215))
        self.fudgeSpin.setSpecialValueText("")
        self.fudgeSpin.setDecimals(3)
        self.fudgeSpin.setMinimum(0.75)
        self.fudgeSpin.setMaximum(1.25)
        self.fudgeSpin.setSingleStep(0.001)
        self.fudgeSpin.setProperty("value", 0.95)
        self.fudgeSpin.setObjectName("fudgeSpin")
        self.gridLayout.addWidget(self.fudgeSpin, 2, 5, 1, 1)
        self.wavelengthSpin = QtWidgets.QSpinBox(self.Settings)
        self.wavelengthSpin.setSpecialValueText("")
        self.wavelengthSpin.setSuffix("")
        self.wavelengthSpin.setMinimum(350)
        self.wavelengthSpin.setMaximum(750)
        self.wavelengthSpin.setProperty("value", 488)
        self.wavelengthSpin.setObjectName("wavelengthSpin")
        self.gridLayout.addWidget(self.wavelengthSpin, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.Settings)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 4, 1, 1)
        self.cropSpin = QtWidgets.QDoubleSpinBox(self.Settings)
        self.cropSpin.setSpecialValueText("")
        self.cropSpin.setDecimals(3)
        self.cropSpin.setMinimum(0.01)
        self.cropSpin.setMaximum(1.0)
        self.cropSpin.setSingleStep(0.01)
        self.cropSpin.setProperty("value", 0.15)
        self.cropSpin.setObjectName("cropSpin")
        self.gridLayout.addWidget(self.cropSpin, 6, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.Settings)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.magSpin = QtWidgets.QDoubleSpinBox(self.Settings)
        self.magSpin.setSpecialValueText("")
        self.magSpin.setDecimals(3)
        self.magSpin.setMinimum(50.0)
        self.magSpin.setMaximum(350.0)
        self.magSpin.setSingleStep(0.001)
        self.magSpin.setProperty("value", 167.364)
        self.magSpin.setObjectName("magSpin")
        self.gridLayout.addWidget(self.magSpin, 5, 1, 1, 1)
        self.PatternPresetsCombo = QtWidgets.QComboBox(self.Settings)
        self.PatternPresetsCombo.setObjectName("PatternPresetsCombo")
        self.PatternPresetsCombo.addItem("")
        self.PatternPresetsCombo.addItem("")
        self.PatternPresetsCombo.addItem("")
        self.PatternPresetsCombo.addItem("")
        self.gridLayout.addWidget(self.PatternPresetsCombo, 0, 4, 1, 2)
        self.writeFileButton = QtWidgets.QPushButton(self.Settings)
        self.writeFileButton.setMinimumSize(QtCore.QSize(0, 40))
        self.writeFileButton.setAutoDefault(False)
        self.writeFileButton.setDefault(False)
        self.writeFileButton.setFlat(False)
        self.writeFileButton.setObjectName("writeFileButton")
        self.gridLayout.addWidget(self.writeFileButton, 6, 4, 1, 2)
        self.autoSpacingCheckBox = QtWidgets.QCheckBox(self.Settings)
        self.autoSpacingCheckBox.setChecked(True)
        self.autoSpacingCheckBox.setObjectName("autoSpacingCheckBox")
        self.gridLayout.addWidget(self.autoSpacingCheckBox, 2, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.Settings)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 6, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.Settings)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.shiftXSpin = QtWidgets.QSpinBox(self.Settings)
        self.shiftXSpin.setSpecialValueText("")
        self.shiftXSpin.setMinimum(-99)
        self.shiftXSpin.setObjectName("shiftXSpin")
        self.gridLayout.addWidget(self.shiftXSpin, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.Settings)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.shiftYSpin = QtWidgets.QSpinBox(self.Settings)
        self.shiftYSpin.setSpecialValueText("")
        self.shiftYSpin.setMinimum(-99)
        self.shiftYSpin.setObjectName("shiftYSpin")
        self.gridLayout.addWidget(self.shiftYSpin, 3, 1, 1, 1)
        self.tiltSpin = QtWidgets.QDoubleSpinBox(self.Settings)
        self.tiltSpin.setSpecialValueText("")
        self.tiltSpin.setDecimals(3)
        self.tiltSpin.setMinimum(-1.5)
        self.tiltSpin.setMaximum(1.5)
        self.tiltSpin.setSingleStep(0.01)
        self.tiltSpin.setProperty("value", 0.0)
        self.tiltSpin.setObjectName("tiltSpin")
        self.gridLayout.addWidget(self.tiltSpin, 4, 1, 1, 1)
        self.tabWidget.addTab(self.Settings, "")
        self.Batch = QtWidgets.QWidget()
        self.Batch.setObjectName("Batch")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Batch)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.Batch)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 7)
        self.label_5 = QtWidgets.QLabel(self.Batch)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.batch_wave = QtWidgets.QLineEdit(self.Batch)
        self.batch_wave.setObjectName("batch_wave")
        self.gridLayout_3.addWidget(self.batch_wave, 1, 1, 1, 6)
        self.label_18 = QtWidgets.QLabel(self.Batch)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 2, 0, 1, 1)
        self.batch_innerNA = QtWidgets.QLineEdit(self.Batch)
        self.batch_innerNA.setObjectName("batch_innerNA")
        self.gridLayout_3.addWidget(self.batch_innerNA, 2, 1, 1, 6)
        self.label_19 = QtWidgets.QLabel(self.Batch)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 3, 0, 1, 1)
        self.batch_outerNA = QtWidgets.QLineEdit(self.Batch)
        self.batch_outerNA.setObjectName("batch_outerNA")
        self.gridLayout_3.addWidget(self.batch_outerNA, 3, 1, 1, 6)
        self.label_20 = QtWidgets.QLabel(self.Batch)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 4, 0, 1, 1)
        self.batch_beamSpacing = QtWidgets.QLineEdit(self.Batch)
        self.batch_beamSpacing.setObjectName("batch_beamSpacing")
        self.gridLayout_3.addWidget(self.batch_beamSpacing, 4, 1, 1, 6)
        self.label_21 = QtWidgets.QLabel(self.Batch)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 5, 0, 1, 1)
        self.batch_xShift = QtWidgets.QLineEdit(self.Batch)
        self.batch_xShift.setMinimumSize(QtCore.QSize(95, 0))
        self.batch_xShift.setObjectName("batch_xShift")
        self.gridLayout_3.addWidget(self.batch_xShift, 5, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.Batch)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 5, 2, 1, 1)
        self.batch_yShift = QtWidgets.QLineEdit(self.Batch)
        self.batch_yShift.setMinimumSize(QtCore.QSize(95, 0))
        self.batch_yShift.setObjectName("batch_yShift")
        self.gridLayout_3.addWidget(self.batch_yShift, 5, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.Batch)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 5, 4, 1, 1)
        self.batch_tilt = QtWidgets.QLineEdit(self.Batch)
        self.batch_tilt.setMinimumSize(QtCore.QSize(120, 0))
        self.batch_tilt.setObjectName("batch_tilt")
        self.gridLayout_3.addWidget(self.batch_tilt, 5, 5, 1, 2)
        self.label_24 = QtWidgets.QLabel(self.Batch)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 6, 0, 1, 1)
        self.batch_outputDir = QtWidgets.QLineEdit(self.Batch)
        self.batch_outputDir.setMinimumSize(QtCore.QSize(100, 0))
        self.batch_outputDir.setObjectName("batch_outputDir")
        self.gridLayout_3.addWidget(self.batch_outputDir, 6, 1, 1, 5)
        self.chooseBatchOutputDir = QtWidgets.QPushButton(self.Batch)
        self.chooseBatchOutputDir.setAutoDefault(False)
        self.chooseBatchOutputDir.setObjectName("chooseBatchOutputDir")
        self.gridLayout_3.addWidget(self.chooseBatchOutputDir, 6, 6, 1, 1)
        self.batchProcessButton = QtWidgets.QPushButton(self.Batch)
        self.batchProcessButton.setEnabled(False)
        self.batchProcessButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setKerning(True)
        self.batchProcessButton.setFont(font)
        self.batchProcessButton.setAutoDefault(False)
        self.batchProcessButton.setObjectName("batchProcessButton")
        self.gridLayout_3.addWidget(self.batchProcessButton, 7, 1, 1, 6)
        self.tabWidget.addTab(self.Batch, "")
        self.SLM = QtWidgets.QWidget()
        self.SLM.setObjectName("SLM")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.SLM)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_14 = QtWidgets.QLabel(self.SLM)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 0, 0, 1, 1)
        self.SLMmodelCombo = QtWidgets.QComboBox(self.SLM)
        self.SLMmodelCombo.setMaximumSize(QtCore.QSize(120, 16777215))
        self.SLMmodelCombo.setObjectName("SLMmodelCombo")
        self.SLMmodelCombo.addItem("")
        self.SLMmodelCombo.addItem("")
        self.gridLayout_4.addWidget(self.SLMmodelCombo, 0, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(320, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.SLM)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 1, 0, 1, 1)
        self.slm_pixelSize_spin = QtWidgets.QDoubleSpinBox(self.SLM)
        self.slm_pixelSize_spin.setMaximumSize(QtCore.QSize(80, 16777215))
        self.slm_pixelSize_spin.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.slm_pixelSize_spin.setSpecialValueText("")
        self.slm_pixelSize_spin.setDecimals(3)
        self.slm_pixelSize_spin.setMinimum(1.0)
        self.slm_pixelSize_spin.setMaximum(50.0)
        self.slm_pixelSize_spin.setSingleStep(0.001)
        self.slm_pixelSize_spin.setProperty("value", 13.662)
        self.slm_pixelSize_spin.setObjectName("slm_pixelSize_spin")
        self.gridLayout_4.addWidget(self.slm_pixelSize_spin, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(358, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 2, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.SLM)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 2, 0, 1, 1)
        self.slm_xpix_spin = QtWidgets.QSpinBox(self.SLM)
        self.slm_xpix_spin.setMaximumSize(QtCore.QSize(80, 16777215))
        self.slm_xpix_spin.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.slm_xpix_spin.setSpecialValueText("")
        self.slm_xpix_spin.setMinimum(1)
        self.slm_xpix_spin.setMaximum(3000)
        self.slm_xpix_spin.setProperty("value", 1280)
        self.slm_xpix_spin.setObjectName("slm_xpix_spin")
        self.gridLayout_4.addWidget(self.slm_xpix_spin, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(358, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 2, 2, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.SLM)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 3, 0, 1, 1)
        self.slm_ypix_spin = QtWidgets.QSpinBox(self.SLM)
        self.slm_ypix_spin.setMaximumSize(QtCore.QSize(80, 16777215))
        self.slm_ypix_spin.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.slm_ypix_spin.setSpecialValueText("")
        self.slm_ypix_spin.setMinimum(1)
        self.slm_ypix_spin.setMaximum(3000)
        self.slm_ypix_spin.setProperty("value", 1024)
        self.slm_ypix_spin.setObjectName("slm_ypix_spin")
        self.gridLayout_4.addWidget(self.slm_ypix_spin, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(358, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 3, 2, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 107, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 4, 3, 1, 1)
        self.tabWidget.addTab(self.SLM, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.autoSpacingCheckBox.clicked['bool'].connect(self.spacingSpin.setDisabled)
        self.autoSpacingCheckBox.clicked['bool'].connect(self.label_4.setDisabled)
        self.autoSpacingCheckBox.clicked['bool'].connect(self.fudgeSpin.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Outer NA:"))
        self.label_4.setText(_translate("Dialog", "Spacing:"))
        self.label_10.setText(_translate("Dialog", "Mag:"))
        self.previewPatternButton.setText(_translate("Dialog", "Preview Pattern"))
        self.label.setText(_translate("Dialog", "Wavelength:"))
        self.label_17.setText(_translate("Dialog", "Shift Y (pix):"))
        self.label_16.setText(_translate("Dialog", "Pattern Presets:"))
        self.fudgeSpin.setToolTip(_translate("Dialog", "Enabling auto spacing will set the spacing to\n"
"factor * wavelength/NA_inner"))
        self.label_9.setText(_translate("Dialog", "# Beams:"))
        self.label_2.setText(_translate("Dialog", "Inner NA:"))
        self.PatternPresetsCombo.setItemText(0, _translate("Dialog", "Manual"))
        self.PatternPresetsCombo.setItemText(1, _translate("Dialog", "Single Bessel"))
        self.PatternPresetsCombo.setItemText(2, _translate("Dialog", "3-Beam Spaced"))
        self.PatternPresetsCombo.setItemText(3, _translate("Dialog", "Square Lattice, Fill Chip"))
        self.writeFileButton.setText(_translate("Dialog", "Write File"))
        self.autoSpacingCheckBox.setToolTip(_translate("Dialog", "Enabling auto spacing will set the spacing to\n"
"factor * wavelength/NA_inner"))
        self.autoSpacingCheckBox.setText(_translate("Dialog", "Auto spacing:"))
        self.label_15.setText(_translate("Dialog", "Crop:"))
        self.label_8.setText(_translate("Dialog", "Shift X (pix):"))
        self.label_7.setText(_translate("Dialog", "Tilt (rad):"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Settings), _translate("Dialog", "Settings"))
        self.label_6.setText(_translate("Dialog", "All fields can be declared as comma seperated lists.  All permutations will be calculated"))
        self.label_5.setText(_translate("Dialog", "wavelength:"))
        self.batch_wave.setPlaceholderText(_translate("Dialog", " e.g.  488, 560, 640"))
        self.label_18.setText(_translate("Dialog", "inner NA:"))
        self.batch_innerNA.setPlaceholderText(_translate("Dialog", " e.g.  0.44, 0.325"))
        self.label_19.setText(_translate("Dialog", "outer NA:"))
        self.batch_outerNA.setPlaceholderText(_translate("Dialog", " e.g.  0.55, 0.40"))
        self.label_20.setText(_translate("Dialog", "(#beam, space):"))
        self.batch_beamSpacing.setPlaceholderText(_translate("Dialog", " e.g.  (1,0), (3, 22), (fill, auto)"))
        self.label_21.setText(_translate("Dialog", "X Shift:"))
        self.batch_xShift.setPlaceholderText(_translate("Dialog", " start-stop-step"))
        self.label_22.setText(_translate("Dialog", "Y Shift:"))
        self.batch_yShift.setPlaceholderText(_translate("Dialog", " start-stop-step"))
        self.label_23.setText(_translate("Dialog", "Tilt:"))
        self.batch_tilt.setPlaceholderText(_translate("Dialog", " start-stop-step"))
        self.label_24.setText(_translate("Dialog", "Output Dir:"))
        self.batch_outputDir.setPlaceholderText(_translate("Dialog", " directory where files will be written..."))
        self.chooseBatchOutputDir.setText(_translate("Dialog", "Choose Dir"))
        self.batchProcessButton.setText(_translate("Dialog", "Feature coming soon..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Batch), _translate("Dialog", "Batch"))
        self.label_14.setText(_translate("Dialog", "SLM model:"))
        self.SLMmodelCombo.setItemText(0, _translate("Dialog", "SXGA-3DM"))
        self.SLMmodelCombo.setItemText(1, _translate("Dialog", "Custom"))
        self.label_11.setText(_translate("Dialog", "Pixel size:"))
        self.label_12.setText(_translate("Dialog", "# pixels X:"))
        self.label_13.setText(_translate("Dialog", "# pixels Y:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SLM), _translate("Dialog", "SLM"))

