{% set name = "llspy" %}
{% set setupdata = load_setup_py_data() %}

package:
  name: {{ name }}
  {% if environ.get('BRANCH') == "master" %}
  version: {{ setupdata['version'] }}
  {% else %}
  version: "{{ GIT_DESCRIBE_TAG }}_{{ GIT_BUILD_STR }}"
  {% endif %}

source:
  # path: ..
  git_url: https://github.com/tlambert03/LLSpy
  git_rev: "{{ environ.get('BRANCH') }}"

build:
  number: 0
  string: 'py{{ PY_VER|replace(".", "") }}_{{ PKG_BUILDNUM }}'
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    {% for key, list in setupdata['entry_points'].items() %}
      {% for item in list %}
    - {{item}}
      {% endfor %}
    {% endfor %}

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy ==1.0.0
    - tifffile ==0.14.0
    - numba ==0.35.0
    - voluptuous ==0.10.5
    - watchdog ==0.8.3
    - pyqt ==5.6.0
    - click ==6.7
    - matplotlib ==2.1.1
    - spimagine ==0.2.2
    - llspylibs
    - pathlib2 # [py2k]
    - configparser # [py2k]
    - pigz
    - lbzip2 # [not win]
    - raven ==6.6.0
    - llspy-slm

test:
  imports:
    - llspy # [not py2k]
  commands:
    # - which lls  # [unix]
    # - where lls  # [win]
    - lls --help # [not py2k]
    - lls gui --test # [not linux]
#    - spimagine

about:
  home: {{ setupdata['url'] }}
  license: {{ setupdata['license'] }}
  license_file: LICENSE
  summary: {{ setupdata['description'] }}

# app:
#   entry: lls-gui
#   icon: ../_assets/llspy_logo.png
#   summary:  "LLSpy GUI"
